export const questQuestions = [
  {
    images: [
      "../quest/bitcoin.jpg",
      "../quest/bitcoin2.jpg",
      "../quest/bitcoin3.jpg",
      "../quest/bitcoin4.jpg",
    ],
    possibleAnswers: [
      "C",
      "B",
      "T",
      "D",
      "O",
      "A",
      "J",
      "Z",
      "A",
      "T",
      "D",
      "O",
      "I",
      "F",
      "F",
      "N",
    ],
    correctAnswer: "BITCOIN",
  },
  {
    images: [
      "../quest/bitcoin4.jpg",
      "../quest/bitcoin.jpg",
      "../quest/bitcoin.jpg",
      "../quest/bitcoin3.jpg",
    ],
    possibleAnswers: [
      "C",
      "B",
      "T",
      "D",
      "T",
      "D",
      "O",
      "I",
      "O",
      "I",
      "T",
      "D",
      "O",
      "I",
      "F",
      "N",
    ],
    correctAnswer: "BITIN",
  },
  {
    images: [
      "../quest/bitcoin.jpg",
      "../quest/bitcoin4.jpg",
      "../quest/bitcoin3.jpg",
      "../quest/bitcoin3.jpg",
    ],
    possibleAnswers: [
      "C",
      "B",
      "T",
      "D",
      "T",
      "D",
      "O",
      "I",
      "O",
      "I",
      "T",
      "D",
      "O",
      "I",
      "F",
      "N",
    ],
    correctAnswer: "BIUUOIN",
  },
  {
    images: [
      "../quest/bitcoin.jpg",
      "../quest/bitcoin.jpg",
      "../quest/bitcoin.jpg",
      "../quest/bitcoin.jpg",
    ],
    possibleAnswers: [
      "C",
      "B",
      "T",
      "D",
      "T",
      "D",
      "O",
      "I",
      "O",
      "I",
      "T",
      "D",
      "O",
      "I",
      "F",
      "N",
    ],
    correctAnswer: "BITCOIN",
  },
  // Add 4 more question objects here
];
